// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: pbapi/plugins.proto

package pbapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Plugins_FetchPreferences_FullMethodName            = "/pbapi.plugins/FetchPreferences"
	Plugins_FetchInstallTasks_FullMethodName           = "/pbapi.plugins/FetchInstallTasks"
	Plugins_DispatchTextEmbeddingInvoke_FullMethodName = "/pbapi.plugins/DispatchTextEmbeddingInvoke"
)

// PluginsClient is the client API for Plugins service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginsClient interface {
	FetchPreferences(ctx context.Context, in *FetchPreferencesRequest, opts ...grpc.CallOption) (*FetchPreferencesReply, error)
	FetchInstallTasks(ctx context.Context, in *FetchInstallTasksRequest, opts ...grpc.CallOption) (*FetchInstallTasksReply, error)
	DispatchTextEmbeddingInvoke(ctx context.Context, in *DispatchTextEmbeddingInvokeRequest, opts ...grpc.CallOption) (*DispatchTextEmbeddingInvokeReply, error)
}

type pluginsClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginsClient(cc grpc.ClientConnInterface) PluginsClient {
	return &pluginsClient{cc}
}

func (c *pluginsClient) FetchPreferences(ctx context.Context, in *FetchPreferencesRequest, opts ...grpc.CallOption) (*FetchPreferencesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchPreferencesReply)
	err := c.cc.Invoke(ctx, Plugins_FetchPreferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginsClient) FetchInstallTasks(ctx context.Context, in *FetchInstallTasksRequest, opts ...grpc.CallOption) (*FetchInstallTasksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchInstallTasksReply)
	err := c.cc.Invoke(ctx, Plugins_FetchInstallTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginsClient) DispatchTextEmbeddingInvoke(ctx context.Context, in *DispatchTextEmbeddingInvokeRequest, opts ...grpc.CallOption) (*DispatchTextEmbeddingInvokeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchTextEmbeddingInvokeReply)
	err := c.cc.Invoke(ctx, Plugins_DispatchTextEmbeddingInvoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginsServer is the server API for Plugins service.
// All implementations must embed UnimplementedPluginsServer
// for forward compatibility.
type PluginsServer interface {
	FetchPreferences(context.Context, *FetchPreferencesRequest) (*FetchPreferencesReply, error)
	FetchInstallTasks(context.Context, *FetchInstallTasksRequest) (*FetchInstallTasksReply, error)
	DispatchTextEmbeddingInvoke(context.Context, *DispatchTextEmbeddingInvokeRequest) (*DispatchTextEmbeddingInvokeReply, error)
	mustEmbedUnimplementedPluginsServer()
}

// UnimplementedPluginsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginsServer struct{}

func (UnimplementedPluginsServer) FetchPreferences(context.Context, *FetchPreferencesRequest) (*FetchPreferencesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchPreferences not implemented")
}
func (UnimplementedPluginsServer) FetchInstallTasks(context.Context, *FetchInstallTasksRequest) (*FetchInstallTasksReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchInstallTasks not implemented")
}
func (UnimplementedPluginsServer) DispatchTextEmbeddingInvoke(context.Context, *DispatchTextEmbeddingInvokeRequest) (*DispatchTextEmbeddingInvokeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DispatchTextEmbeddingInvoke not implemented")
}
func (UnimplementedPluginsServer) mustEmbedUnimplementedPluginsServer() {}
func (UnimplementedPluginsServer) testEmbeddedByValue()                 {}

// UnsafePluginsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginsServer will
// result in compilation errors.
type UnsafePluginsServer interface {
	mustEmbedUnimplementedPluginsServer()
}

func RegisterPluginsServer(s grpc.ServiceRegistrar, srv PluginsServer) {
	// If the following call panics, it indicates UnimplementedPluginsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Plugins_ServiceDesc, srv)
}

func _Plugins_FetchPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchPreferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginsServer).FetchPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugins_FetchPreferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginsServer).FetchPreferences(ctx, req.(*FetchPreferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugins_FetchInstallTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchInstallTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginsServer).FetchInstallTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugins_FetchInstallTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginsServer).FetchInstallTasks(ctx, req.(*FetchInstallTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugins_DispatchTextEmbeddingInvoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchTextEmbeddingInvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginsServer).DispatchTextEmbeddingInvoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugins_DispatchTextEmbeddingInvoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginsServer).DispatchTextEmbeddingInvoke(ctx, req.(*DispatchTextEmbeddingInvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Plugins_ServiceDesc is the grpc.ServiceDesc for Plugins service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Plugins_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbapi.plugins",
	HandlerType: (*PluginsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchPreferences",
			Handler:    _Plugins_FetchPreferences_Handler,
		},
		{
			MethodName: "FetchInstallTasks",
			Handler:    _Plugins_FetchInstallTasks_Handler,
		},
		{
			MethodName: "DispatchTextEmbeddingInvoke",
			Handler:    _Plugins_DispatchTextEmbeddingInvoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pbapi/plugins.proto",
}
