syntax = "proto3";

package pbapi;

option go_package="mlib.com/gofy/server/proto/pbapi";

import "exceptions/exceptions.proto";


service tools {
  rpc GetToolLabelsList(GetToolLabelsListRequest) returns (GetToolLabelsListReply) {}
  rpc GetToolProviderList(GetToolProviderListRequest) returns (GetToolProviderListReply) {}
  rpc GetToolList(GetToolListRequest) returns (GetToolListReply) {}	  
  rpc GetMCPToolList(GetMCPToolListRequest) returns (GetMCPToolListReply) {}	  
}

message GetToolLabelsListRequest {

}
message GetToolLabelsListReply{
	exceptions.HTTPException exp = 1;
  string tool_labels_list_str = 2;
}
message GetToolProviderListRequest {
  string type = 1;
  string account_id = 2;
  string tenant_id = 3;
}
message GetToolProviderListReply{
	exceptions.HTTPException exp = 1;
  string providers_str = 2;
}
message GetToolListRequest {
  string type = 1;
  string account_id = 2;
  string tenant_id = 3;  
}
message GetToolListReply {
	exceptions.HTTPException exp = 1;
  string tools_str = 2;
}
message GetMCPToolListRequest {
  string tenant_id = 1;  
}
message GetMCPToolListReply {
	exceptions.HTTPException exp = 1;
  string tools_str = 2;
}