// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.11.2
// source: pbapi/tools.proto

package pbapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tools_GetToolLabelsList_FullMethodName   = "/pbapi.tools/GetToolLabelsList"
	Tools_GetToolProviderList_FullMethodName = "/pbapi.tools/GetToolProviderList"
	Tools_GetToolList_FullMethodName         = "/pbapi.tools/GetToolList"
	Tools_GetMCPToolList_FullMethodName      = "/pbapi.tools/GetMCPToolList"
)

// ToolsClient is the client API for Tools service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ToolsClient interface {
	GetToolLabelsList(ctx context.Context, in *GetToolLabelsListRequest, opts ...grpc.CallOption) (*GetToolLabelsListReply, error)
	GetToolProviderList(ctx context.Context, in *GetToolProviderListRequest, opts ...grpc.CallOption) (*GetToolProviderListReply, error)
	GetToolList(ctx context.Context, in *GetToolListRequest, opts ...grpc.CallOption) (*GetToolListReply, error)
	GetMCPToolList(ctx context.Context, in *GetMCPToolListRequest, opts ...grpc.CallOption) (*GetMCPToolListReply, error)
}

type toolsClient struct {
	cc grpc.ClientConnInterface
}

func NewToolsClient(cc grpc.ClientConnInterface) ToolsClient {
	return &toolsClient{cc}
}

func (c *toolsClient) GetToolLabelsList(ctx context.Context, in *GetToolLabelsListRequest, opts ...grpc.CallOption) (*GetToolLabelsListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToolLabelsListReply)
	err := c.cc.Invoke(ctx, Tools_GetToolLabelsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolsClient) GetToolProviderList(ctx context.Context, in *GetToolProviderListRequest, opts ...grpc.CallOption) (*GetToolProviderListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToolProviderListReply)
	err := c.cc.Invoke(ctx, Tools_GetToolProviderList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolsClient) GetToolList(ctx context.Context, in *GetToolListRequest, opts ...grpc.CallOption) (*GetToolListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToolListReply)
	err := c.cc.Invoke(ctx, Tools_GetToolList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolsClient) GetMCPToolList(ctx context.Context, in *GetMCPToolListRequest, opts ...grpc.CallOption) (*GetMCPToolListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMCPToolListReply)
	err := c.cc.Invoke(ctx, Tools_GetMCPToolList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolsServer is the server API for Tools service.
// All implementations must embed UnimplementedToolsServer
// for forward compatibility.
type ToolsServer interface {
	GetToolLabelsList(context.Context, *GetToolLabelsListRequest) (*GetToolLabelsListReply, error)
	GetToolProviderList(context.Context, *GetToolProviderListRequest) (*GetToolProviderListReply, error)
	GetToolList(context.Context, *GetToolListRequest) (*GetToolListReply, error)
	GetMCPToolList(context.Context, *GetMCPToolListRequest) (*GetMCPToolListReply, error)
	mustEmbedUnimplementedToolsServer()
}

// UnimplementedToolsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToolsServer struct{}

func (UnimplementedToolsServer) GetToolLabelsList(context.Context, *GetToolLabelsListRequest) (*GetToolLabelsListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToolLabelsList not implemented")
}
func (UnimplementedToolsServer) GetToolProviderList(context.Context, *GetToolProviderListRequest) (*GetToolProviderListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToolProviderList not implemented")
}
func (UnimplementedToolsServer) GetToolList(context.Context, *GetToolListRequest) (*GetToolListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToolList not implemented")
}
func (UnimplementedToolsServer) GetMCPToolList(context.Context, *GetMCPToolListRequest) (*GetMCPToolListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMCPToolList not implemented")
}
func (UnimplementedToolsServer) mustEmbedUnimplementedToolsServer() {}
func (UnimplementedToolsServer) testEmbeddedByValue()               {}

// UnsafeToolsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolsServer will
// result in compilation errors.
type UnsafeToolsServer interface {
	mustEmbedUnimplementedToolsServer()
}

func init() {
	grpc.RegisterServiceDesc(&Tools_ServiceDesc)
}
func RegisterToolsServer(s grpc.ServiceRegistrar, srv ToolsServer) {
	// If the following call panics, it indicates UnimplementedToolsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tools_ServiceDesc, srv)
}

func _Tools_GetToolLabelsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToolLabelsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolsServer).GetToolLabelsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tools_GetToolLabelsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolsServer).GetToolLabelsList(ctx, req.(*GetToolLabelsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tools_GetToolProviderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToolProviderListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolsServer).GetToolProviderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tools_GetToolProviderList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolsServer).GetToolProviderList(ctx, req.(*GetToolProviderListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tools_GetToolList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToolListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolsServer).GetToolList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tools_GetToolList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolsServer).GetToolList(ctx, req.(*GetToolListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tools_GetMCPToolList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMCPToolListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolsServer).GetMCPToolList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tools_GetMCPToolList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolsServer).GetMCPToolList(ctx, req.(*GetMCPToolListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tools_ServiceDesc is the grpc.ServiceDesc for Tools service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tools_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbapi.tools",
	HandlerType: (*ToolsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetToolLabelsList",
			Handler:    _Tools_GetToolLabelsList_Handler,
		},
		{
			MethodName: "GetToolProviderList",
			Handler:    _Tools_GetToolProviderList_Handler,
		},
		{
			MethodName: "GetToolList",
			Handler:    _Tools_GetToolList_Handler,
		},
		{
			MethodName: "GetMCPToolList",
			Handler:    _Tools_GetMCPToolList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pbapi/tools.proto",
}
