// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.11.2
// source: entities/app.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Import struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id" form:"id"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status" form:"status"`
	AppId              string                 `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id" form:"app_id"`
	CurrentDslVersion  string                 `protobuf:"bytes,4,opt,name=current_dsl_version,json=currentDslVersion,proto3" json:"current_dsl_version" form:"current_dsl_version"`
	ImportedDslVersion string                 `protobuf:"bytes,5,opt,name=imported_dsl_version,json=importedDslVersion,proto3" json:"imported_dsl_version" form:"imported_dsl_version"`
	Error              string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error" form:"error"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Import) Reset() {
	*x = Import{}
	mi := &file_entities_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Import) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Import) ProtoMessage() {}

func (x *Import) ProtoReflect() protoreflect.Message {
	mi := &file_entities_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Import.ProtoReflect.Descriptor instead.
func (*Import) Descriptor() ([]byte, []int) {
	return file_entities_app_proto_rawDescGZIP(), []int{0}
}

func (x *Import) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Import) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Import) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Import) GetCurrentDslVersion() string {
	if x != nil {
		return x.CurrentDslVersion
	}
	return ""
}

func (x *Import) GetImportedDslVersion() string {
	if x != nil {
		return x.ImportedDslVersion
	}
	return ""
}

func (x *Import) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PendingData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ImportMode     string                 `protobuf:"bytes,1,opt,name=import_mode,json=importMode,proto3" json:"import_mode" form:"import_mode"`
	YamlContent    string                 `protobuf:"bytes,2,opt,name=yaml_content,json=yamlContent,proto3" json:"yaml_content" form:"yaml_content"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name" form:"name"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description" form:"description"`
	IconType       string                 `protobuf:"bytes,5,opt,name=icon_type,json=iconType,proto3" json:"icon_type" form:"icon_type"`
	Icon           string                 `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon" form:"icon"`
	IconBackground string                 `protobuf:"bytes,7,opt,name=icon_background,json=iconBackground,proto3" json:"icon_background" form:"icon_background"`
	AppId          string                 `protobuf:"bytes,8,opt,name=app_id,json=appId,proto3" json:"app_id" form:"app_id"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PendingData) Reset() {
	*x = PendingData{}
	mi := &file_entities_app_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingData) ProtoMessage() {}

func (x *PendingData) ProtoReflect() protoreflect.Message {
	mi := &file_entities_app_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingData.ProtoReflect.Descriptor instead.
func (*PendingData) Descriptor() ([]byte, []int) {
	return file_entities_app_proto_rawDescGZIP(), []int{1}
}

func (x *PendingData) GetImportMode() string {
	if x != nil {
		return x.ImportMode
	}
	return ""
}

func (x *PendingData) GetYamlContent() string {
	if x != nil {
		return x.YamlContent
	}
	return ""
}

func (x *PendingData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PendingData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PendingData) GetIconType() string {
	if x != nil {
		return x.IconType
	}
	return ""
}

func (x *PendingData) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *PendingData) GetIconBackground() string {
	if x != nil {
		return x.IconBackground
	}
	return ""
}

func (x *PendingData) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

var File_entities_app_proto protoreflect.FileDescriptor

var file_entities_app_proto_rawDesc = string([]byte{
	0x0a, 0x12, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2f, 0x61, 0x70, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0xbf,
	0x01, 0x0a, 0x06, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x13, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x5f, 0x64, 0x73, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x73,
	0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x14, 0x69, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x73, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64,
	0x44, 0x73, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0xf8, 0x01, 0x0a, 0x0b, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x4d, 0x6f, 0x64,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x79, 0x61, 0x6d, 0x6c, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x79, 0x61, 0x6d, 0x6c, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x63,
	0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69,
	0x63, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x69,
	0x63, 0x6f, 0x6e, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x63, 0x6f, 0x6e, 0x42, 0x61, 0x63, 0x6b, 0x67, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x42, 0x2e, 0x5a, 0x2c, 0x6d,
	0x6c, 0x69, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x66, 0x79, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x3b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_entities_app_proto_rawDescOnce sync.Once
	file_entities_app_proto_rawDescData []byte
)

func file_entities_app_proto_rawDescGZIP() []byte {
	file_entities_app_proto_rawDescOnce.Do(func() {
		file_entities_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_app_proto_rawDesc), len(file_entities_app_proto_rawDesc)))
	})
	return file_entities_app_proto_rawDescData
}

var file_entities_app_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_entities_app_proto_goTypes = []any{
	(*Import)(nil),      // 0: entities.Import
	(*PendingData)(nil), // 1: entities.PendingData
}
var file_entities_app_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entities_app_proto_init() }
func file_entities_app_proto_init() {
	if File_entities_app_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_app_proto_rawDesc), len(file_entities_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_app_proto_goTypes,
		DependencyIndexes: file_entities_app_proto_depIdxs,
		MessageInfos:      file_entities_app_proto_msgTypes,
	}.Build()
	File_entities_app_proto = out.File
	file_entities_app_proto_goTypes = nil
	file_entities_app_proto_depIdxs = nil
}
